export const ENV = {
  get appId() { return process.env.VITE_APP_ID ?? ""; },
  get cookieSecret() { return process.env.JWT_SECRET ?? ""; },
  get databaseUrl() { return process.env.DATABASE_URL ?? ""; },
  get databaseSsl() { return process.env.DATABASE_SSL === "true"; },
  get oAuthServerUrl() { return process.env.OAUTH_SERVER_URL ?? ""; },
  get ownerOpenId() { return process.env.OWNER_OPEN_ID ?? ""; },
  get isProduction() { return process.env.NODE_ENV === "production"; },
  get forgeApiUrl() { return process.env.BUILT_IN_FORGE_API_URL ?? ""; },
  get forgeApiKey() { return process.env.BUILT_IN_FORGE_API_KEY ?? ""; },
  get vapidPublicKey() { return process.env.VAPID_PUBLIC_KEY ?? ""; },
  get vapidPrivateKey() { return process.env.VAPID_PRIVATE_KEY ?? ""; },
  get vapidSubject() { return process.env.VAPID_SUBJECT ?? "mailto:ssbmbwuugame@gmail.com"; },
  get virusTotalApiKey() { return process.env.VIRUSTOTAL_API_KEY ?? ""; },
};
